# This is a basic workflow to help you get started with Actions

name: pdfgen

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  package:
    # Job name is Greeting
    name: Generate and package
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate
        uses: docker://orendu/pandoc:latest
        with:
          entryPoint: /generate.sh
          args: README.md Readme.pdf "ReadMe"
        id: gen
        
      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v2
        with:
          name: storage_arch_docs
          path: Readme.pdf
