# This is a basic workflow to help you get started with Actions

name: pdfgen

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  package:
    # Job name is Greeting
    name: Generate and package
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Generate
        uses: docker://orendu/pandoc:latest
        with:
          entryPoint: /usr/bin/pandoc
          args: --from gfm --to html5 -N --standalone -M title=Readme -o Readme.pdf /github/workspace/README.md
        id: gen
      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v2
        with:
          name: storage_arch_docs
          path: Readme.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Readme.pdf
          asset_name: Readme.pdf
          asset_content_type: application/pdf
